# Generated by Django 2.2.2 on 2019-06-12 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.IntegerField(blank=True)),
                ('temperature', models.IntegerField(blank=True)),
                ('motifs', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenParaclinique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeExamen', models.CharField(max_length=50)),
                ('nomExamen', models.CharField(max_length=50)),
                ('datePrescription', models.DateField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='her_app.Consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomTraitement', models.CharField(max_length=50)),
                ('posologieTrait', models.CharField(max_length=50)),
                ('datePrescritpion', models.DateField(auto_now=True)),
                ('dureeTrait', models.CharField(max_length=50)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='her_app.Consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('numIdentNational', models.CharField(max_length=17)),
                ('dateNaissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nationalite', models.CharField(max_length=50)),
                ('situationMatri', models.CharField(choices=[('M', 'Marié(e)'), ('C', 'Célibataire')], max_length=1)),
                ('profession', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('numIdentNational', models.CharField(max_length=17)),
                ('dateNaissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nationalite', models.CharField(max_length=50)),
                ('specialite', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LieuTravail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=50)),
                ('nomHopital', models.CharField(max_length=50)),
                ('medecin', models.ManyToManyField(related_name='lieuTravails', to='her_app.Medecin')),
            ],
        ),
        migrations.CreateModel(
            name='HypotheseDiagnostique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMaladie', models.CharField(max_length=50)),
                ('Remarques', models.CharField(blank=True, max_length=300)),
                ('Confirmation', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to='her_app.Consultation')),
            ],
        ),
        migrations.CreateModel(
            name='FichierExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeFichier', models.CharField(max_length=50)),
                ('nomFichier', models.CharField(max_length=50)),
                ('examenparaclinique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='her_app.ExamenParaclinique')),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medecin', models.ManyToManyField(related_name='dossiers', to='her_app.Medecin')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='her_app.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='her_app.DossierMedical'),
        ),
        migrations.CreateModel(
            name='Antecedant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeAntecedant', models.CharField(choices=[('A', 'Allergies'), ('C', 'Chirurgicaux'), ('F', 'Familiaux')], max_length=1)),
                ('nomAntecedant', models.CharField(max_length=50)),
                ('remarquesAntecedant', models.CharField(max_length=50)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='her_app.DossierMedical')),
            ],
        ),
    ]
