# Generated by Django 2.2.2 on 2019-06-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her_app', '0002_auto_20190612_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='numIdentNational',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='numIdentNational',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
