# Generated by Django 2.2.2 on 2019-06-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('her_app', '0004_antecedant_essai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedant',
            name='essai',
        ),
    ]
