# Generated by Django 2.2.2 on 2019-06-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('her_app', '0005_remove_antecedant_essai'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Antecedant',
        ),
    ]
