# Generated by Django 2.2.2 on 2019-06-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her_app', '0009_consultation_dateconsultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='dateConsultation',
            field=models.DateField(),
        ),
    ]
