# Generated by Django 2.2.2 on 2019-06-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her_app', '0011_consultation_finconsultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='hypothesesC',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
