# Generated by Django 2.2.2 on 2019-06-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her_app', '0016_auto_20190624_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichierexamen',
            name='fichier',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
