# Generated by Django 2.2.2 on 2019-06-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('her_app', '0017_fichierexamen_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichierexamen',
            name='examenparaclinique',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fichier', to='her_app.ExamenParaclinique'),
        ),
    ]
