# Generated by Django 2.2.2 on 2019-07-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her_app', '0019_auto_20190630_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='diagnostic',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
