# Generated by Django 2.2.2 on 2019-07-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her_app', '0021_auto_20190706_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='nomHopital',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='ville',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
